// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfkmfcgnvpglrkqhnaiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impma21mY2dudnBnbHJrcWhuYWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjA3MDUsImV4cCI6MjA2NDU5NjcwNX0.wOncYy7MW8xTY2NQN5hFgQRQEp5g4BYU_B167wExRk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);